# Generated by Django 4.1.1 on 2022-10-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="footertext",
            options={"verbose_name_plural": "Footer text"},
        ),
    ]
