# Generated by Django 4.1.1 on 2022-10-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0002_alter_footertext_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footertext",
            name="name",
        ),
    ]
